### ISSUE TITLE
发布项目提示未激活

### ISSUE THREAD

**Issue by caixw** [sadne/partake#12]
发布项目提示未激活，是不是需要邮箱验证才行？
而我的github.com邮箱默认是不公开的，所以就没了。不过也没找到哪里可以设置邮箱的。

**Comment by sadne** [comment]
激活是后台管理员激活的，因为我不希望任何人进来就能发布项目，我需要能够控制质量

**Comment by caixw** [comment]
哦，原来是这样啊

**Comment by caixw** [comment]
不过我觉得还不如提交之后，后台再审核是否可以发布更合理些，就是工作量可能会比较大些。

**Comment by sadne** [comment]
都有，不过我觉得，别人提交后审核如果删掉的话，会很怪，我把你的激活吧

**Comment by caixw** [comment]
其实我也没东西发，就是到了一个新网站，总想试试它的功能:blush:
